server:
  port: 8080

######Druid数据源配置######
# JDBC配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # allowMultiQueries=true 允许批量更新
    url: jdbc:mysql://127.0.0.1:3306/db_novel?allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 30

# logger Config
logging:
  level:
    com.nines.novel: debug

# mapper.xml 位置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.nines.novel.entity